remote_theme: daviddarnes/alembic

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# Site Settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Code With Friends"
description: "A month-long coding event to build new tech with a supportive online community"
logo: "/assets/logos/cwf2020_logo.png"

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: Projects
    url: /project_fair/
  # - title: How To Enter
  #   url: /how_to_join/
  # - title: Community
  #   url: /community/
  # - title: Resources
  #   url: /resources/

navigation_footer:
  - title: Created by Mayuko Inoue and Scott Kwang
    url: https://hellomayuko.com
